apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocp-dog.fullname" . }}-backend-api
  labels:
    {{- include "ocp-dog.labels" . | nindent 4 }}
    tier: backend
spec:
  replicas: {{ .Values.replicaCount.backendApi }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      component: backend-api
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        component: backend-api
        tier: backend
    spec:
      containers:
        - name: backend-api
          image: {{ include "ocp-dog.image" .Values.images.backendApi }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.backendApi.targetPort }}
              name: http
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ocp-dog.fullname" . }}-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ocp-dog.fullname" . }}-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "ocp-dog.fullname" . }}-db
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "ocp-dog.fullname" . }}-db
                  key: DB_PASS
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 45
            periodSeconds: 30
