apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocp-dog.fullname" . }}-backend-api
  labels:
    {{- include "ocp-dog.labels" . | nindent 4 }}
    tier: backend
spec:
  type: {{ .Values.service.backendApi.type }}
  selector:
    app: {{ .Values.app.name }}
    component: backend-api
  ports:
    - port: {{ .Values.service.backendApi.port }}
      targetPort: {{ .Values.service.backendApi.targetPort }}
      name: http
      protocol: TCP
