apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocp-dog.fullname" . }}-database
  labels:
    {{- include "ocp-dog.labels" . | nindent 4 }}
    tier: database
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name }}
    component: database
  ports:
    - port: {{ .Values.service.database.port }}
      targetPort: {{ .Values.service.database.port }}
      protocol: TCP
      name: tcp
