apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocp-dog.fullname" . }}-frontend
  labels:
    {{- include "ocp-dog.labels" . | nindent 4 }}
    tier: frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        component: frontend
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: {{ include "ocp-dog.image" .Values.images.frontend }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.frontend.targetPort }}
              name: http
          env:
            - name: FRONTEND_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ocp-dog.fullname" . }}-config
                  key: FRONTEND_API_URL
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
