apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "ocp-dog.fullname" . }}-frontend
  labels:
    {{- include "ocp-dog.labels" . | nindent 4 }}
    tier: frontend
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "ocp-dog.fullname" . }}-frontend
    weight: 100
  port:
    targetPort: http
  tls:
    termination: {{ .Values.route.tlsTermination }}
  wildcardPolicy: None
