apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocp-dog.fullname" . }}-frontend
  labels:
    {{- include "ocp-dog.labels" . | nindent 4 }}
    tier: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app: {{ .Values.app.name }}
    component: frontend
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
      protocol: TCP
      name: http
