apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocp-dog.fullname" . }}-frontend-api
  labels:
    {{- include "ocp-dog.labels" . | nindent 4 }}
    tier: api
spec:
  type: {{ .Values.service.frontendApi.type }}
  selector:
    app: {{ .Values.app.name }}
    component: frontend-api
  ports:
    - port: {{ .Values.service.frontendApi.port }}
      targetPort: {{ .Values.service.frontendApi.targetPort }}
      name: http
      protocol: TCP
