apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ocp-dog.fullname" . }}-backend-api
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app.name }}
      component: backend-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.app.name }}
              component: frontend-api
      ports:
        - protocol: TCP
          port: {{ .Values.service.backendApi.port }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.app.name }}
              component: database
      ports:
        - protocol: TCP
          port: {{ .Values.service.database.port }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
