apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ocp-dog.fullname" . }}-frontend
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app.name }}
      component: frontend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
      ports:
        - protocol: TCP
          port: {{ .Values.service.frontend.port }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.app.name }}
              component: frontend-api
      ports:
        - protocol: TCP
          port: {{ .Values.service.frontendApi.port }}
