{{- if and .Values.networkPolicy.enabled (default true .Values.networkPolicy.allowDns) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ocp-dog.fullname" . }}-allow-dns
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app.name }}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              {{ default "kubernetes.io/metadata.name" .Values.networkPolicy.dns.namespaceLabel }}: {{ default "openshift-dns" .Values.networkPolicy.dns.namespaceValue }}
      ports:
        {{- range $port := (default (list 53 5353) .Values.networkPolicy.dns.ports) }}
        - protocol: UDP
          port: {{ $port }}
        - protocol: TCP
          port: {{ $port }}
        {{- end }}
{{- end }}
