apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ocp-dog.fullname" . }}-database
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app.name }}
      component: database
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.app.name }}
              component: backend-api
      ports:
        - protocol: TCP
          port: {{ .Values.service.database.port }}
