{{- $routesOrder := list "frontend" "frontendApi" -}}
{{- $root := . -}}
{{- $lastIndex := sub (len $routesOrder) 1 -}}
{{- range $idx, $name := $routesOrder }}
{{- $route := index $root.Values.route $name }}
{{- $component := default $name $route.component }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "ocp-dog.fullname" $root }}-{{ $component }}
  labels:
    {{- include "ocp-dog.labels" $root | nindent 4 }}
    tier: {{ default "frontend" $route.tier }}
spec:
  host: {{ $route.host }}
  to:
    kind: Service
    name: {{ include "ocp-dog.fullname" $root }}-{{ $component }}
    weight: 100
  port:
    targetPort: {{ default "http" $route.portName }}
  {{- if $route.tlsTermination }}
  tls:
    termination: {{ $route.tlsTermination }}
  {{- end }}
  wildcardPolicy: None
{{- if lt $idx $lastIndex }}
---
{{- end }}
{{- end }}
