{{- $order := list "frontend" "frontendApi" -}}
{{- $last := sub (len $order) 1 -}}
{{- $root := . -}}
{{- range $idx, $name := $order }}
{{- $route := index $root.Values.route $name }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "ocp-dog.fullname" $root }}-{{ $route.component }}
  labels:
    {{- include "ocp-dog.labels" $root | nindent 4 }}
    tier: {{ $route.tier }}
spec:
  host: {{ $route.host }}
  to:
    kind: Service
    name: {{ include "ocp-dog.fullname" $root }}-{{ $route.component }}
    weight: 100
  port:
    targetPort: {{ default "http" $route.portName }}
  {{- if $route.tlsTermination }}
  tls:
    termination: {{ $route.tlsTermination }}
  {{- end }}
  wildcardPolicy: None
{{- if lt $idx $last }}
---
{{- end }}
{{- end }}
