apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocp-dog.fullname" . }}-db
  labels:
    {{- include "ocp-dog.labels" . | nindent 4 }}
    tier: database
stringData:
  DB_USER: {{ .Values.secrets.databaseUser | quote }}
  DB_PASS: {{ .Values.secrets.databasePassword | quote }}
